name: Release the Docker image

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
     name: Publish image to Docker Hub
     runs-on: ubuntu-latest
     env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: ${{ vars.PORT }}
     steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test env
        run: echo "Hello $PORT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            PORT=${{ vars.PORT }}
          tags: yutharsans/simple-phone-book:latest

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
